// src/components/Box.tsx
import { Component, createMemo, For, Index, Show } from 'solid-js';
import shuffle from 'lodash.shuffle';
import { GraphDisplayer, MachineBox } from '../graph';
import { pseudoRandom, replicate } from '../util';

type BoxComponent = Component <{
  displayer: GraphDisplayer,
  colors: string[],
  idx: number,
  box: MachineBox,
}>

const Box: BoxComponent = props => {
  const position = createMemo(() => props.displayer.position(props.idx));
  const label = () => props.displayer.vertexLabel(props.idx);
  const balls = createMemo(() => shuffle(props.box.flatMap(({nbBalls, edge}) => replicate(nbBalls, edge))));
  const height = () =>  Math.min(95, balls().length);
  const segments = () => {
    const segs = [];
    const total = props.box.reduce((acc, {nbBalls}) => acc+nbBalls, 0); 
    let psum = 0;
    for (const {nbBalls, edge} of props.box) {
      segs.push({begin: psum / total, end: (psum+nbBalls)/total, edge});
      psum += nbBalls;
    }
    return segs;
  }

  return (
    <Show when={position()}>
      <g style={{
        transform: `translate(${position()!.x}px, ${position()!.y}px)`
      }}>
        <path
          d="M1 1 L10 109 L90 109 L99 1"
          stroke-width="3.0"
          stroke="#000"
          fill="transparent"
        />
        <For each={balls()}>
          {((color, i) => (
            <circle
              cx={15 + pseudoRandom(props.idx + i()) * 71}
              cy={100 - pseudoRandom(10 + props.idx + i()) * height()}
              r="5"
              fill={props.colors[color]}
            />
          ))}
        </For>
        <Index each={segments()}>
          {seg => (
            <rect
              x={3.0 + 94.0 * seg().begin}
              y="115"
              width={94.0 * (seg().end - seg().begin)}
              height="20"
              stroke="black"
              fill={props.colors[seg().edge]}
            />
          )}
        </Index>
        <Show when={label()}>
          <text x="50" y="150">{label()}</text>
        </Show>
      </g>
    </Show>
  )
}

export default Box;

// src/components/Box.svelte
<script lang="ts">
  import { arrayOf, sumBy } from '@gbagan/utils';
  import type { GraphDisplayer, MachineBox } from '../lib/graph';
  import { pseudoRandom, pseudoShuffle } from '../lib/util';

  type Props = {
    displayer: GraphDisplayer;
    colors: string[];
    idx: number;
    box: MachineBox;
  }

  let {displayer, colors, idx, box}: Props = $props();

  let position = $derived(displayer.position(idx));
  let label = $derived(displayer.vertexLabel(idx));
  let balls = $derived(pseudoShuffle(
    box.flatMap(({nbBalls, edge}) => arrayOf(nbBalls, edge))
  ));
  let segments = $derived.by(() => {
    let total = sumBy(box, b => b.nbBalls);
    const segs = [];
    let psum = 0;
    for (const {nbBalls, edge} of box) {
      segs.push({ begin: psum / total, end: (psum + nbBalls) / total, edge });
      psum += nbBalls;
    }
    return segs;
  });
</script>

{#if position !== null}
  {@const height = Math.min(95, balls.length)}
  <g style:transform="translate({position.x}px, {position.y}px)">
    <path
      d="M1 1 L10 109 L90 109 L99 1"
      stroke-width="3.0"
      stroke="#000"
      fill="transparent"
    />
    {#each balls as color, i}
      <circle
        cx={15 + pseudoRandom(idx + i) * 71}
        cy={100 - pseudoRandom(10 + idx + i) * height}
        r="5"
        fill={colors[color]}
      />
    {/each}
    {#each segments as {begin, end, edge}}
      <rect
        x={3 + 94 * begin}
        y="115"
        width={94 * (end - begin)}
        height="20"
        stroke="black"
        fill={colors[edge]}
      />
    {/each}
    {#if label !== null}
      <text x="50" y="150">{label}</text>
    {/if}
  </g>
{/if}
