// src/components/Machine.svelte
<script lang="ts">
  import type { GraphDisplayer, Machine } from "../lib/graph";
  import Box from "./Box.svelte";

  type Props = {
    displayer: GraphDisplayer;
    colors: string[];
    machine: Machine;
  }

  let { displayer, colors, machine}: Props = $props();
</script>

<div class="container">
  <svg viewBox="0 0 {displayer.width} {displayer.height}">
    {#each machine as box, idx}
      <Box {displayer} {colors} {idx} {box} />
    {/each}
  </svg>
</div>

<style>
  .container {
    width: 40rem;
  }
</style>

// src/components/Machine.tsx
import { Component, Index } from "solid-js"
import { GraphDisplayer, Machine } from "../graph"
import Box from "./Box"

type MachineComponent = Component <{
  displayer: GraphDisplayer,
  colors: string[],
  machine: Machine,
}>

const MachineView: MachineComponent = props => (
  <div class="w-[40rem]">
    <svg viewBox={`0 0 ${props.displayer.width} ${props.displayer.height}`}>
      <Index each={props.machine}>
        {(box, idx) => <Box displayer={props.displayer} colors={props.colors} idx={idx} box={box()}/>}
      </Index>
    </svg>
  </div>
)

export default MachineView
